# This is a basic workflow to help you get started with Actions

name: Main CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: install node env
        uses: actions/setup-node@v3.1.0
        with:
          node-version: '14.x'
        
      - name: install yarn
        run: npm install yarn -g
        
      - name: install project dependencies
        run: yarn

      - name: build project
        run: yarn build

      - name: scp ssh pipelines
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          # first_ssh: |
          #   cd ${{ secrets.TARGET }} &&
          #   rm -rf *
          scp: |
            ./dist/* => ${{ secrets.TARGET }}
         
      